### Locator

### Function name: great_circle_distance

Calculate the great circle distance (in metres) between pairs of points specified as latitude and longitude on a spherical Earth (with radius 6371 km).

Input: 

**latlon1** : arraylike latitudes and longitudes of first point (as [n, 2] array for n points)

**latlon2** : arraylike latitudes and longitudes of second point (as [m, 2] array for m points)

Output: 

**Distance**: Distance in metres between each pair of points (as an n x m array)

### Example

In [3]:
from armageddon.locator import great_circle_distance, PostcodeLocator

For example, to calculate the great circle distance between *[ 54.0, 0.0 ]* and *[ 55, 1.0 ]* and diatance between *[ 55.0, 0.0 ]* and *[ 55, 1 .0 ]* at the same time, we could use the code below

In [4]:
import numpy as np
fmt = lambda x: np.format_float_scientific(x, precision=3)
with np.printoptions(formatter={'all': fmt}):
   print(great_circle_distance([[54.0, 0.0], [55, 0.0]], [55, 1.0]))

[[1.286e+05]
 [6.378e+04]]


Calculate the great circle distance between *[[ 54.0, 0.0 ], [ 55.0, 1.0 ], [ 54.2, -3.0 ]]* and *[[ 55.0, 1.0 ], [ 56.0, -2.1 ], [ 54.001, -0.003 ]]* in pairs

In [5]:
pnts1 = np.array([[54.0, 0.0], [55.0, 1.0], [54.2, -3.0]])
pnts2 = np.array([[55.0, 1.0], [56.0, -2.1], [54.001, -0.003]])
with np.printoptions(formatter={'all': fmt}):
   print(great_circle_distance(pnts1, pnts2))

[[1.286e+05 2.596e+05 2.254e+02]
 [9.494e-02 2.247e+05 1.286e+05]
 [2.725e+05 2.082e+05 1.966e+05]]


### Function name: get_postcodes_by_radius

Return (unit or sector) postcodes within specific distances of input location.

Input: 

**X** : arraylike Latitude-longitude pair of centre location

**radii** : arraylike array of radial distances from X

**sector** : bool, optional if true return postcode sectors, otherwise postcode units

Output: 

**place_list**: Contains the lists of postcodes closer than the elements of radii to the location X.

### Example

For example, the code below shows how to get postcodes within 0.13e3 meters of location coordinate (51.4981, -0.1773)

<div>
<img src="example.jpg" width="500"/>
</div>

In [6]:
locator = PostcodeLocator('../resources/full_postcodes.csv', '../resources/population_by_postcode_sector.csv')
locator.get_postcodes_by_radius((51.4981, -0.1773), [0.13e3])

[['SW7 2BU', 'SW7 2DD', 'SW7 5HF', 'SW7 5HG', 'SW7 2BT', 'SW7 5HQ', 'SW7 2AZ']]

The code below shows postcode sectors in different circles

<div>
<img src="example2.jpg" width="500"/>
</div>

In [7]:
locator.get_postcodes_by_radius((51.4981, -0.1773), [0.4e3, 0.2e3], True)

[['SW7  1', 'SW7  5', 'SW7  3', 'SW7  9', 'SW7  4', 'SW7  2'],
 ['SW7  1', 'SW7  5', 'SW7  3', 'SW7  9', 'SW7  4', 'SW7  2']]

### Function name: get_population_of_postcode

Return populations of a list of postcode units or sectors.

Input: 

**postcodes** : list of postcode units or postcode sectors

**sector** : bool, if true return populations for postcode sectors, otherwise returns populations for postcode units

Output: 

**global_pc**: Contains the populations of input postcode units or sectors

### Example

To calculate population of different postcode units, just input them as a list

In [8]:
locator.get_population_of_postcode([['SW7 2AZ', 'SW7 2BT', 'SW7 2BU', 'SW7 2DD']])

[[19, 19, 19, 19]]

To calculate population of different postcode sectors, just input them as a list and add **True**

In [9]:
locator.get_population_of_postcode([['SW7  2']], True)

[[2283]]